name: Setup nx job
description: Install NodeJS, set shas and install dependencies.

runs:
  using: composite
  steps:
    # Use a temporary file to concat summaries since GitHub doesn't do it for composite actions.
    # Last step will print its content to the $GITHUB_STEP_SUMMARY variable
    - name: Fetch metadata about this project (Node, PNPM version, etc...)
      shell: bash
      id: metadata
      run: |
        # echo "package_manager=$([[ -f ./yarn.lock ]] && echo "yarn" || ([[ -f ./pnpm-lock.yaml ]] && echo "pnpm") || echo "npm")" >> $GITHUB_OUTPUT
        echo "node_version=$(jq -r '.volta.node' package.json)" >> $GITHUB_OUTPUT
        echo "pnpm_version=$(jq -r '.volta.pnpm' package.json)" >> $GITHUB_OUTPUT

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - name: Install NodeJS with Volta
      uses: volta-cli/action@v4

    - name: Install PNPM
      if: steps.metadata.outputs.package_manager == 'pnpm'
      uses: pnpm/action-setup@v2.2.2
      with:
        version: ${{ steps.metadata.outputs.pnpm_version }}

    - name: Use the node_modules cache if available [pnpm]
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-node-${{ steps.metadata.outputs.node_version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-node-${{ steps.metadata.outputs.node_version }}-

    - shell: bash
      run: pnpm install --frozen-lockfile
