name: Setup nx job
description: Install NodeJS, set shas and install dependencies.

runs:
  using: composite
  steps:
    - uses: nrwl/nx-set-shas@v3

    - uses: volta-cli/action@v4

    - shell: bash
      id: metadata
      run: |
        echo "node_version=$(node --version)" >> $GITHUB_OUTPUT
        echo "yarn_cache_dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Use the node_modules cache if available [yarn]
      uses: actions/cache@v2
      with:
        path: ${{ steps.metadata.outputs.yarn_cache_dir }}
        key: ${{ runner.os }}-node-${{ steps.metadata.outputs.node_version }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.metadata.outputs.node_version }}-yarn-

    - shell: bash
      run: yarn install --frozen-lockfile
